analyzer:
  exclude:
    - build/**
    - android/**
    - windows/**
    - linux/**
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
